import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "en" | "ar";

type TranslationValue = {
	en: string;
	ar: string;
};

const STORAGE_KEY = "wellness:language";

const translations: Record<string, TranslationValue> = {
	"Dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
	"Browse Catalog": { en: "Browse Catalog", ar: "تصفح الكتالوج" },
	"Browse Suppliers": { en: "Browse Suppliers", ar: "تصفح الموردين" },
	"My Products": { en: "My Products", ar: "منتجاتي" },
	"My Orders": { en: "My Orders", ar: "طلباتي" },
	"Discover Suppliers": { en: "Discover Suppliers", ar: "اكتشف الموردين" },
	"Supplier View": { en: "Supplier View", ar: "عرض المورد" },
	"Supplier Workflow": { en: "Supplier Workflow", ar: "مسار عمل المورد" },
	"Buyer Workspace": { en: "Buyer Workspace", ar: "مساحة المشتري" },
	"Supplier Workspace": { en: "Supplier Workspace", ar: "مساحة المورد" },
	"Health Ecosystem": { en: "Health Ecosystem", ar: "منظومة الصحة" },
	"Categories": { en: "Categories", ar: "الفئات" },
	"Curated": { en: "Curated", ar: "مختار بعناية" },
	"New Arrivals": { en: "New Arrivals", ar: "وصل حديثًا" },
	"New Arrivals From Your Suppliers": { en: "New Arrivals From Your Suppliers", ar: "الواردات الجديدة من مورديك" },
	"No new arrivals yet": { en: "No new arrivals yet", ar: "لا توجد واردات جديدة بعد" },
	"Your subscribed suppliers have not published anything new in the last few days.": { en: "Your subscribed suppliers have not published anything new in the last few days.", ar: "لم ينشر الموردون الذين تتابعهم أي منتجات جديدة خلال الأيام الماضية." },
	"Subscribe to suppliers to tailor your feed": { en: "Subscribe to suppliers to tailor your feed", ar: "اشترك في الموردين لتخصيص موجزك" },
	"Follow the suppliers you trust and we will surface their newest listings here first.": { en: "Follow the suppliers you trust and we will surface their newest listings here first.", ar: "تابع الموردين الذين تثق بهم وسنعرض أحدث منتجاتهم هنا أولًا." },
	"Supplier Products": { en: "Supplier Products", ar: "منتجات المورد" },
	"All Products": { en: "All Products", ar: "كل المنتجات" },
	"Product Catalog": { en: "Product Catalog", ar: "كتالوج المنتجات" },
	"My Product Catalog": { en: "My Product Catalog", ar: "كتالوج منتجاتي" },
	"Shop Products": { en: "Shop Products", ar: "منتجات المتجر" },
	"No products found": { en: "No products found", ar: "لم يتم العثور على منتجات" },
	"Try adjusting your search or category filter.": { en: "Try adjusting your search or category filter.", ar: "جرّب تعديل البحث أو فلتر الفئة." },
	"Added to cart": { en: "Added to cart", ar: "تمت الإضافة إلى السلة" },
	"Details": { en: "Details", ar: "التفاصيل" },
	"Insights": { en: "Insights", ar: "التحليلات" },
	"Add": { en: "Add", ar: "أضف" },
	"In stock": { en: "In stock", ar: "متوفر" },
	"Cart": { en: "Cart", ar: "السلة" },
	"Review the products in your cart, adjust quantities, and continue to checkout when you are ready.": { en: "Review the products in your cart, adjust quantities, and continue to checkout when you are ready.", ar: "راجع المنتجات في السلة، وعدّل الكميات، ثم تابع إلى الدفع عندما تكون جاهزًا." },
	"Your cart is empty": { en: "Your cart is empty", ar: "سلتك فارغة" },
	"Browse our catalog to add products.": { en: "Browse our catalog to add products.", ar: "تصفح الكتالوج لإضافة منتجات." },
	"Subtotal": { en: "Subtotal", ar: "الإجمالي الفرعي" },
	"Proceed to Checkout": { en: "Proceed to Checkout", ar: "المتابعة إلى الدفع" },
	"Clear Cart": { en: "Clear Cart", ar: "تفريغ السلة" },
	"Stay Informed on Supplier Demand": { en: "Stay Informed on Supplier Demand", ar: "ابقَ على اطلاع على طلب الموردين" },
	"Stay Informed": { en: "Stay Informed", ar: "ابقَ على اطلاع" },
	"Your email": { en: "Your email", ar: "بريدك الإلكتروني" },
	"Saving...": { en: "Saving...", ar: "جارٍ الحفظ..." },
	"Subscribe": { en: "Subscribe", ar: "اشترك" },
	"You are subscribed": { en: "You are subscribed", ar: "تم الاشتراك" },
	"We will send supplier-focused updates to your inbox.": { en: "We will send supplier-focused updates to your inbox.", ar: "سنرسل لك تحديثات موجهة للموردين إلى بريدك." },
	"We will keep you posted with relevant supplier and product updates.": { en: "We will keep you posted with relevant supplier and product updates.", ar: "سنوافيك بالتحديثات المناسبة الخاصة بالموردين والمنتجات." },
	"Subscription failed": { en: "Subscription failed", ar: "فشل الاشتراك" },
	"Unable to subscribe right now.": { en: "Unable to subscribe right now.", ar: "تعذر الاشتراك الآن." },
	"Platform": { en: "Platform", ar: "المنصة" },
	"Support": { en: "Support", ar: "الدعم" },
	"Contact": { en: "Contact", ar: "التواصل" },
	"Help Center": { en: "Help Center", ar: "مركز المساعدة" },
	"Shipping Info": { en: "Shipping Info", ar: "معلومات الشحن" },
	"Returns": { en: "Returns", ar: "المرتجعات" },
	"Privacy Policy": { en: "Privacy Policy", ar: "سياسة الخصوصية" },
	"Terms of Service": { en: "Terms of Service", ar: "شروط الخدمة" },
	"Back to home": { en: "Back to home", ar: "العودة إلى الصفحة الرئيسية" },
	"Continue with Google": { en: "Continue with Google", ar: "المتابعة باستخدام Google" },
	"or": { en: "or", ar: "أو" },
	"Sign In": { en: "Sign In", ar: "تسجيل الدخول" },
	"Register": { en: "Register", ar: "إنشاء حساب" },
	"Email": { en: "Email", ar: "البريد الإلكتروني" },
	"Password": { en: "Password", ar: "كلمة المرور" },
	"Signing in...": { en: "Signing in...", ar: "جارٍ تسجيل الدخول..." },
	"I am a": { en: "I am a", ar: "أنا" },
	"Business Name": { en: "Business Name", ar: "اسم النشاط" },
	"Phone": { en: "Phone", ar: "الهاتف" },
	"Creating account...": { en: "Creating account...", ar: "جارٍ إنشاء الحساب..." },
	"Register as": { en: "Register as", ar: "التسجيل كم" },
	"Buyer": { en: "Buyer", ar: "مشتري" },
	"Supplier": { en: "Supplier", ar: "مورد" },
	"One more step": { en: "One more step", ar: "خطوة أخيرة" },
	"Tell us how you'll use Wellness so we can set up your account correctly.": { en: "Tell us how you'll use Wellness so we can set up your account correctly.", ar: "أخبرنا كيف ستستخدم Wellness حتى نعد حسابك بشكل صحيح." },
	"Continue as": { en: "Continue as", ar: "المتابعة كـ" },
	"Protected ordering": { en: "Protected ordering", ar: "طلب محمي" },
	"Live stock visibility": { en: "Live stock visibility", ar: "عرض حي للمخزون" },
	"Supplier-first fulfilment": { en: "Supplier-first fulfilment", ar: "تنفيذ يركز على المورد" },
	"Actionable demand signals": { en: "Actionable demand signals", ar: "إشارات طلب قابلة للتنفيذ" },
	"Egypt's 1st B2B Online Pharmaceutical Platform": { en: "Egypt's 1st B2B Online Pharmaceutical Platform", ar: "أول منصة مصرية لبيع الأدوية عبر B2B" },
	"Run Your Supplier Operation From One Screen": { en: "Run Your Supplier Operation From One Screen", ar: "أدر عمليات المورد من شاشة واحدة" },
	"Track demand, inspect product performance, manage orders, and update your listings without leaving your workflow.": { en: "Track demand, inspect product performance, manage orders, and update your listings without leaving your workflow.", ar: "تابع الطلب، وراجع أداء المنتجات، وأدر الطلبات، وحدّث قوائمك دون مغادرة سير عملك." },
	"Wholesale pharmaceutical solutions with competitive pricing, verified products, and seamless ordering for pharmacies across Egypt.": { en: "Wholesale pharmaceutical solutions with competitive pricing, verified products, and seamless ordering for pharmacies across Egypt.", ar: "حلول دوائية بالجملة بأسعار تنافسية ومنتجات موثقة وطلب سلس للصيدليات في مختلف أنحاء مصر." },
	"Supplier Operations": { en: "Supplier Operations", ar: "عمليات المورد" },
	"Trusted B2B Platform": { en: "Trusted B2B Platform", ar: "منصة B2B موثوقة" },
	"Search": { en: "Search", ar: "بحث" },
	"Search medicines, vitamins...": { en: "Search medicines, vitamins...", ar: "ابحث عن الأدوية والفيتامينات..." },
	"Search your products...": { en: "Search your products...", ar: "ابحث في منتجاتك..." },
	"Join Wellness": { en: "Join Wellness", ar: "انضم إلى Wellness" },
	"Supplier": { en: "Supplier", ar: "المورد" },
	"Suppliers": { en: "Suppliers", ar: "الموردون" },
	"Deals": { en: "Deals", ar: "العروض" },
	"Notifications": { en: "Notifications", ar: "الإشعارات" },
	"Pending Orders": { en: "Pending Orders", ar: "الطلبات المعلقة" },
	"Supplier Updates": { en: "Supplier Updates", ar: "تحديثات المورد" },
	"New Arrivals": { en: "New Arrivals", ar: "وصل حديثًا" },
	"New Order Requests": { en: "New Order Requests", ar: "طلبات جديدة" },
	"Sign in": { en: "Sign in", ar: "تسجيل الدخول" },
	"Sign out": { en: "Sign out", ar: "تسجيل الخروج" },
	"Checkout": { en: "Checkout", ar: "إتمام الشراء" },
	"Delivery Details": { en: "Delivery Details", ar: "تفاصيل التوصيل" },
	"Delivery Address": { en: "Delivery Address", ar: "عنوان التوصيل" },
	"City": { en: "City", ar: "المدينة" },
	"Postal Code": { en: "Postal Code", ar: "الرمز البريدي" },
	"Order Notes": { en: "Order Notes", ar: "ملاحظات الطلب" },
	"(optional)": { en: "(optional)", ar: "(اختياري)" },
	"Special delivery instructions...": { en: "Special delivery instructions...", ar: "تعليمات خاصة للتوصيل..." },
	"Payment Method": { en: "Payment Method", ar: "طريقة الدفع" },
	"Pay Online": { en: "Pay Online", ar: "الدفع أونلاين" },
	"Secure card payment": { en: "Secure card payment", ar: "دفع آمن بالبطاقة" },
	"Demo mode — no real charge yet": { en: "Demo mode — no real charge yet", ar: "وضع تجريبي - لا توجد عملية خصم فعلية بعد" },
	"Pay when your order arrives": { en: "Pay when your order arrives", ar: "ادفع عند وصول طلبك" },
	"Order Summary": { en: "Order Summary", ar: "ملخص الطلب" },
	"Delivery": { en: "Delivery", ar: "التوصيل" },
	"Free": { en: "Free", ar: "مجاني" },
	"Total": { en: "Total", ar: "الإجمالي" },
	"Processing...": { en: "Processing...", ar: "جارٍ المعالجة..." },
	"Place Order": { en: "Place Order", ar: "تأكيد الطلب" },
	"Pay Now": { en: "Pay Now", ar: "ادفع الآن" },
	"Please sign in": { en: "Please sign in", ar: "يرجى تسجيل الدخول" },
	"You need to be logged in to place an order.": { en: "You need to be logged in to place an order.", ar: "يجب تسجيل الدخول لتقديم طلب." },
	"Supplier accounts cannot place buyer orders": { en: "Supplier accounts cannot place buyer orders", ar: "لا يمكن لحسابات الموردين إنشاء طلبات مشتري" },
	"Switch to a buyer account to check out products.": { en: "Switch to a buyer account to check out products.", ar: "انتقل إلى حساب مشتري لإتمام شراء المنتجات." },
	"Order placed successfully! 🎉": { en: "Order placed successfully! 🎉", ar: "تم تقديم الطلب بنجاح! 🎉" },
	"Order failed": { en: "Order failed", ar: "فشل الطلب" },
	"Order": { en: "Order", ar: "الطلب" },
	"is pending supplier confirmation.": { en: "is pending supplier confirmation.", ar: "بانتظار تأكيد المورد." },
	"We'll notify you as suppliers confirm.": { en: "We'll notify you as suppliers confirm.", ar: "سنخطرك مع تأكيد الموردين." },
	"Add products before checking out.": { en: "Add products before checking out.", ar: "أضف منتجات قبل إتمام الشراء." },
	"Product not found": { en: "Product not found", ar: "المنتج غير موجود" },
	"The product you tried to open is no longer available.": { en: "The product you tried to open is no longer available.", ar: "المنتج الذي حاولت فتحه لم يعد متاحًا." },
	"Go Back": { en: "Go Back", ar: "الرجوع" },
	"Suppliers only manage their own products": { en: "Suppliers only manage their own products", ar: "الموردون يديرون منتجاتهم فقط" },
	"Open your product catalog to review insights for your own listings.": { en: "Open your product catalog to review insights for your own listings.", ar: "افتح كتالوج منتجاتك لمراجعة التحليلات الخاصة بقوائمك." },
	"Added to favorites": { en: "Added to favorites", ar: "تمت الإضافة إلى المفضلة" },
	"Removed from favorites": { en: "Removed from favorites", ar: "تمت الإزالة من المفضلة" },
	"You can come back to this product anytime.": { en: "You can come back to this product anytime.", ar: "يمكنك العودة إلى هذا المنتج في أي وقت." },
	"This product is no longer in your favorites.": { en: "This product is no longer in your favorites.", ar: "هذا المنتج لم يعد ضمن مفضلتك." },
	"Buyer account required": { en: "Buyer account required", ar: "يلزم حساب مشتري" },
	"Sign in with a buyer account to use this action.": { en: "Sign in with a buyer account to use this action.", ar: "سجّل الدخول بحساب مشتري لاستخدام هذا الإجراء." },
	"Supplier subscribed": { en: "Supplier subscribed", ar: "تمت متابعة المورد" },
	"Subscription removed": { en: "Subscription removed", ar: "تم إلغاء المتابعة" },
	"New arrivals from this supplier will show up in your feed.": { en: "New arrivals from this supplier will show up in your feed.", ar: "ستظهر أحدث منتجات هذا المورد في موجزك." },
	"Their new arrivals will no longer be highlighted for you.": { en: "Their new arrivals will no longer be highlighted for you.", ar: "لن يتم إبراز أحدث منتجاتهم لك بعد الآن." },
	"Product updated": { en: "Product updated", ar: "تم تحديث المنتج" },
	"Your product changes are live.": { en: "Your product changes are live.", ar: "تحديثات منتجك أصبحت مباشرة." },
	"Update failed": { en: "Update failed", ar: "فشل التحديث" },
	"Unable to update product.": { en: "Unable to update product.", ar: "تعذر تحديث المنتج." },
	"Saved": { en: "Saved", ar: "تم الحفظ" },
	"Add to Favorites": { en: "Add to Favorites", ar: "أضف إلى المفضلة" },
	"Subscribe to Supplier": { en: "Subscribe to Supplier", ar: "متابعة المورد" },
	"Product Insights": { en: "Product Insights", ar: "تحليلات المنتج" },
	"Units Sold": { en: "Units Sold", ar: "الوحدات المباعة" },
	"Latest Order": { en: "Latest Order", ar: "آخر طلب" },
	"No orders yet": { en: "No orders yet", ar: "لا توجد طلبات بعد" },
	"Edit Product": { en: "Edit Product", ar: "تعديل المنتج" },
	"Product Name": { en: "Product Name", ar: "اسم المنتج" },
	"Description": { en: "Description", ar: "الوصف" },
	"Stock": { en: "Stock", ar: "المخزون" },
	"Unit": { en: "Unit", ar: "الوحدة" },
	"Image URL": { en: "Image URL", ar: "رابط الصورة" },
	"Save Changes": { en: "Save Changes", ar: "حفظ التغييرات" },
	"Supplier Snapshot": { en: "Supplier Snapshot", ar: "نظرة عامة على المورد" },
	"This supplier": { en: "This supplier", ar: "هذا المورد" },
	"offers this product with wholesale-friendly minimums and live stock visibility.": { en: "offers this product with wholesale-friendly minimums and live stock visibility.", ar: "يقدم هذا المنتج بحدود دنيا مناسبة للبيع بالجملة مع عرض حي للمخزون." },
	"Business": { en: "Business", ar: "النشاط" },
	"Why it matters": { en: "Why it matters", ar: "لماذا هذا مهم" },
	"Subscribe to this supplier to surface their fresh listings in your new-arrivals feed.": { en: "Subscribe to this supplier to surface their fresh listings in your new-arrivals feed.", ar: "تابع هذا المورد لتظهر أحدث قوائمه في موجز الواردات الجديدة." },
	"Buyer Checklist": { en: "Buyer Checklist", ar: "قائمة المشتري" },
	"Review the description and minimum order before adding this listing to your cart.": { en: "Review the description and minimum order before adding this listing to your cart.", ar: "راجع الوصف والحد الأدنى للطلب قبل إضافة هذا المنتج إلى السلة." },
	"Save it to favorites if you want to compare it with similar products later.": { en: "Save it to favorites if you want to compare it with similar products later.", ar: "احفظه في المفضلة إذا أردت مقارنته بمنتجات مشابهة لاحقًا." },
	"Subscribe to this supplier to keep their newest posts in your buyer dashboard feed.": { en: "Subscribe to this supplier to keep their newest posts in your buyer dashboard feed.", ar: "تابع هذا المورد لتبقى أحدث منشوراته في موجز لوحة المشتري لديك." },
	"Orders for This Product": { en: "Orders for This Product", ar: "طلبات هذا المنتج" },
	"No orders have been placed for this product yet.": { en: "No orders have been placed for this product yet.", ar: "لم يتم تقديم أي طلبات لهذا المنتج بعد." },
	"Similar Products": { en: "Similar Products", ar: "منتجات مشابهة" },
	"You may also want to compare": { en: "You may also want to compare", ar: "قد ترغب أيضًا في المقارنة" },
	"No similar products yet": { en: "No similar products yet", ar: "لا توجد منتجات مشابهة بعد" },
	"We will show alternatives from the same category here as more products arrive.": { en: "We will show alternatives from the same category here as more products arrive.", ar: "سنُظهر بدائل من الفئة نفسها هنا مع توفر المزيد من المنتجات." },
	"Supplier directory is built for buyers": { en: "Supplier directory is built for buyers", ar: "دليل الموردين مخصص للمشترين" },
	"Suppliers manage their own listings and orders instead of subscribing to other suppliers.": { en: "Suppliers manage their own listings and orders instead of subscribing to other suppliers.", ar: "يدير الموردون قوائمهم وطلباتهم بدلًا من متابعة موردين آخرين." },
	"Open Supplier Dashboard": { en: "Open Supplier Dashboard", ar: "فتح لوحة المورد" },
	"Buyer Subscriptions": { en: "Buyer Subscriptions", ar: "اشتراكات المشتري" },
	"Supplier Directory": { en: "Supplier Directory", ar: "دليل الموردين" },
	"Browse all suppliers on Wellness, subscribe to the ones you trust, and bring their newest products into your new-arrivals feed.": { en: "Browse all suppliers on Wellness, subscribe to the ones you trust, and bring their newest products into your new-arrivals feed.", ar: "تصفح كل الموردين على Wellness، واتبِع من تثق بهم، وأدخل أحدث منتجاتهم إلى موجز الواردات الجديدة." },
	"Sign in to personalize supplier subscriptions": { en: "Sign in to personalize supplier subscriptions", ar: "سجّل الدخول لتخصيص اشتراكات الموردين" },
	"Buyers can follow suppliers and unlock a tailored new-arrivals feed.": { en: "Buyers can follow suppliers and unlock a tailored new-arrivals feed.", ar: "يمكن للمشترين متابعة الموردين وفتح موجز مخصص للواردات الجديدة." },
	"No suppliers matched your search": { en: "No suppliers matched your search", ar: "لم يطابق بحثك أي موردين" },
	"Try a broader search to discover more supplier partners.": { en: "Try a broader search to discover more supplier partners.", ar: "جرّب بحثًا أوسع لاكتشاف مزيد من شركاء التوريد." },
	"Subscriptions": { en: "Subscriptions", ar: "الاشتراكات" },
	"Newest Listing": { en: "Newest Listing", ar: "أحدث قائمة" },
	"No products yet": { en: "No products yet", ar: "لا توجد منتجات بعد" },
	"Latest Product": { en: "Latest Product", ar: "آخر منتج" },
	"Supplier has not listed products yet": { en: "Supplier has not listed products yet", ar: "لم يدرج المورد منتجات بعد" },
	"Subscribed": { en: "Subscribed", ar: "تمت المتابعة" },
	"View All Products": { en: "View All Products", ar: "عرض كل المنتجات" },
	"No orders in this range": { en: "No orders in this range", ar: "لا توجد طلبات ضمن هذا النطاق" },
	"Try a wider range or place new orders to see dashboard activity here.": { en: "Try a wider range or place new orders to see dashboard activity here.", ar: "جرّب نطاقًا أوسع أو أنشئ طلبات جديدة لرؤية نشاط لوحة التحكم هنا." },
	"Pending Supplier Confirmations": { en: "Pending Supplier Confirmations", ar: "الطلبات بانتظار تأكيد المورد" },
	"Active Orders": { en: "Active Orders", ar: "الطلبات النشطة" },
	"All Orders": { en: "All Orders", ar: "كل الطلبات" },
	"Waiting for": { en: "Waiting for", ar: "بانتظار" },
	"to confirm": { en: "to confirm", ar: "للتأكيد" },
	"No pending confirmations right now.": { en: "No pending confirmations right now.", ar: "لا توجد تأكيدات معلقة الآن." },
	"Confirmed supplier updates will appear here.": { en: "Confirmed supplier updates will appear here.", ar: "ستظهر تحديثات المورد المؤكدة هنا." },
	"Cash on Delivery": { en: "Cash on Delivery", ar: "الدفع عند الاستلام" },
	"Online Payment": { en: "Online Payment", ar: "دفع إلكتروني" },
	"Product": { en: "Product", ar: "المنتج" },
	"Qty": { en: "Qty", ar: "الكمية" },
	"Delivery to": { en: "Delivery to", ar: "التوصيل إلى" },
	"Time Range": { en: "Time Range", ar: "النطاق الزمني" },
	"Select range": { en: "Select range", ar: "اختر النطاق" },
	"Total Orders": { en: "Total Orders", ar: "إجمالي الطلبات" },
	"Total Spent": { en: "Total Spent", ar: "إجمالي الإنفاق" },
	"Subscriptions": { en: "Subscriptions", ar: "الاشتراكات" },
	"Favorites": { en: "Favorites", ar: "المفضلة" },
	"Supplier Subscriptions": { en: "Supplier Subscriptions", ar: "اشتراكات الموردين" },
	"Active subscriptions": { en: "Active subscriptions", ar: "الاشتراكات النشطة" },
	"Pending orders": { en: "Pending orders", ar: "الطلبات المعلقة" },
	"Follow suppliers to tailor your new-arrivals feed around the catalogs you care about most.": { en: "Follow suppliers to tailor your new-arrivals feed around the catalogs you care about most.", ar: "تابع الموردين لتخصيص موجز الواردات الجديدة حول الكتالوجات التي تهمك أكثر." },
	"Favorite products from product detail pages to keep quick access to them here.": { en: "Favorite products from product detail pages to keep quick access to them here.", ar: "أضف المنتجات من صفحات التفاصيل إلى المفضلة لتصل إليها بسرعة هنا." },
	"Open product details": { en: "Open product details", ar: "فتح تفاصيل المنتج" },
	"No pending orders.": { en: "No pending orders.", ar: "لا توجد طلبات معلقة." },
	"No supplier updates yet.": { en: "No supplier updates yet.", ar: "لا توجد تحديثات من الموردين بعد." },
	"Subscribe to suppliers to see tailored new arrivals.": { en: "Subscribe to suppliers to see tailored new arrivals.", ar: "تابع الموردين لرؤية الواردات الجديدة المخصصة." },
	"New Order Requests": { en: "New Order Requests", ar: "طلبات جديدة" },
	"Review payment and fulfilment details": { en: "Review payment and fulfilment details", ar: "راجع تفاصيل الدفع والتنفيذ" },
	"No new order requests.": { en: "No new order requests.", ar: "لا توجد طلبات جديدة." },
	"account": { en: "account", ar: "حساب" },
	"supplier": { en: "supplier", ar: "المورد" },
	"Browse Products": { en: "Browse Products", ar: "تصفح المنتجات" },
	"No listed products yet": { en: "No listed products yet", ar: "لا توجد منتجات منشورة بعد" },
	"Add your first product to start appearing across the platform.": { en: "Add your first product to start appearing across the platform.", ar: "أضف أول منتج لك لتبدأ بالظهور على المنصة." },
	"This view is tailored to supplier activity, not buyer shopping.": { en: "This view is tailored to supplier activity, not buyer shopping.", ar: "هذا العرض مخصص لنشاط المورد وليس لتسوق المشتري." },
	"As a supplier, this area is dedicated to your own catalog and performance.": { en: "As a supplier, this area is dedicated to your own catalog and performance.", ar: "بصفتك موردًا، هذه المساحة مخصصة لكتالوجك وأدائك." },
	"Add products, then inspect demand in one place": { en: "Add products, then inspect demand in one place", ar: "أضف المنتجات ثم راجع الطلب في مكان واحد" },
	"Open My Products": { en: "Open My Products", ar: "افتح منتجاتي" },
	"Latest Listings": { en: "Latest Listings", ar: "أحدث القوائم" },
	"You have not listed any products yet": { en: "You have not listed any products yet", ar: "لم تنشر أي منتجات بعد" },
	"Open My Products to add your first listing.": { en: "Open My Products to add your first listing.", ar: "افتح منتجاتي لإضافة أول قائمة لك." },
	"Suppliers only see and manage their own listings here.": { en: "Suppliers only see and manage their own listings here.", ar: "يرى الموردون ويديرون قوائمهم الخاصة فقط هنا." },
	"Browse our full range of pharmaceutical products.": { en: "Browse our full range of pharmaceutical products.", ar: "تصفح مجموعتنا الكاملة من المنتجات الدوائية." },
	"Add products before checking out.": { en: "Add products before checking out.", ar: "أضف منتجات قبل إتمام الشراء." },
	"Your cart is empty": { en: "Your cart is empty", ar: "سلتك فارغة" },
	"Browse Catalog": { en: "Browse Catalog", ar: "تصفح الكتالوج" },
	"Product Images": { en: "Product Images", ar: "صور المنتج" },
	"Remove": { en: "Remove", ar: "إزالة" },
	"Add Another Image": { en: "Add Another Image", ar: "إضافة صورة أخرى" },
	"Select category": { en: "Select category", ar: "اختر الفئة" },
	"No orders yet": { en: "No orders yet", ar: "لا توجد طلبات بعد" },
	"Go Home": { en: "Go Home", ar: "العودة للرئيسية" },
	"Supplier access only": { en: "Supplier access only", ar: "الوصول للموردين فقط" },
	"This area is reserved for supplier accounts managing listings and fulfilment.": { en: "This area is reserved for supplier accounts managing listings and fulfilment.", ar: "هذه المساحة مخصصة لحسابات الموردين التي تدير القوائم والتنفيذ." },
	"Add Product": { en: "Add Product", ar: "إضافة منتج" },
	"Save failed": { en: "Save failed", ar: "فشل الحفظ" },
	"Unable to save product.": { en: "Unable to save product.", ar: "تعذر حفظ المنتج." },
	"Product added": { en: "Product added", ar: "تمت إضافة المنتج" },
	"Product deleted": { en: "Product deleted", ar: "تم حذف المنتج" },
	"Unable to delete product.": { en: "Unable to delete product.", ar: "تعذر حذف المنتج." },
	"Order status updated": { en: "Order status updated", ar: "تم تحديث حالة الطلب" },
	"Unable to update order status.": { en: "Unable to update order status.", ar: "تعذر تحديث حالة الطلب." },
	"Track demand, update listings, and manage every order requested from your catalog.": { en: "Track demand, update listings, and manage every order requested from your catalog.", ar: "تابع الطلب، وحدّث القوائم، وأدر كل طلب وارد من كتالوجك." },
	"Revenue": { en: "Revenue", ar: "الإيرادات" },
	"Orders": { en: "Orders", ar: "الطلبات" },
	"Active Products": { en: "Active Products", ar: "المنتجات النشطة" },
	"Low Stock": { en: "Low Stock", ar: "المخزون المنخفض" },
	"Top Product Insights": { en: "Top Product Insights", ar: "أهم تحليلات المنتجات" },
	"Add your first product to start measuring demand and profit.": { en: "Add your first product to start measuring demand and profit.", ar: "أضف أول منتج لك لبدء قياس الطلب والربح." },
	"Demand": { en: "Demand", ar: "الطلب" },
	"Profit": { en: "Profit", ar: "الربح" },
	"units": { en: "units", ar: "وحدات" },
	"units sold": { en: "units sold", ar: "وحدة مباعة" },
	"Latest Orders": { en: "Latest Orders", ar: "آخر الطلبات" },
	"Orders from buyers in the selected range will appear here as soon as they come in.": { en: "Orders from buyers in the selected range will appear here as soon as they come in.", ar: "ستظهر طلبات المشترين في النطاق المحدد هنا فور ورودها." },
	"My Products": { en: "My Products", ar: "منتجاتي" },
	"My Orders": { en: "My Orders", ar: "طلباتي" },
	"No products match your search.": { en: "No products match your search.", ar: "لا توجد منتجات تطابق بحثك." },
	"You have not listed any products yet. Add one to start tracking demand and profit.": { en: "You have not listed any products yet. Add one to start tracking demand and profit.", ar: "لم تنشر أي منتجات بعد. أضف واحدًا للبدء في تتبع الطلب والربح." },
	"No buyer orders in the selected range yet. Once pharmacies place requests from your listings, they will appear here with payment and status details.": { en: "No buyer orders in the selected range yet. Once pharmacies place requests from your listings, they will appear here with payment and status details.", ar: "لا توجد طلبات مشترين في النطاق المحدد بعد. عندما تطلب الصيدليات من قوائمك، ستظهر هنا مع تفاصيل الدفع والحالة." },
	"line items": { en: "line items", ar: "بنود" },
	"Edit": { en: "Edit", ar: "تعديل" },
	"Delete": { en: "Delete", ar: "حذف" },
	"Product updated": { en: "Product updated", ar: "تم تحديث المنتج" },
	"You can come back to this product anytime.": { en: "You can come back to this product anytime.", ar: "يمكنك العودة إلى هذا المنتج في أي وقت." },
	"Unable to save product.": { en: "Unable to save product.", ar: "تعذر حفظ المنتج." },
	"File too large": { en: "File too large", ar: "الملف كبير جدًا" },
	"Invalid file": { en: "Invalid file", ar: "ملف غير صالح" },
	"Please select an image.": { en: "Please select an image.", ar: "يرجى اختيار صورة." },
	"Max size is 5MB.": { en: "Max size is 5MB.", ar: "الحد الأقصى 5 ميغابايت." },
	"Image uploaded": { en: "Image uploaded", ar: "تم رفع الصورة" },
	"Upload failed": { en: "Upload failed", ar: "فشل الرفع" },
	"Upload image": { en: "Upload image", ar: "رفع صورة" },
	"Replace": { en: "Replace", ar: "استبدال" },
	"Oops! Page not found": { en: "Oops! Page not found", ar: "عفوًا! الصفحة غير موجودة" },
	"Return to Home": { en: "Return to Home", ar: "العودة إلى الرئيسية" },
	"Account type saved": { en: "Account type saved", ar: "تم حفظ نوع الحساب" },
	"Registered as": { en: "Registered as", ar: "مسجل كـ" },
	"Unable to save account type.": { en: "Unable to save account type.", ar: "تعذر حفظ نوع الحساب." },
	"Welcome back!": { en: "Welcome back!", ar: "مرحبًا بعودتك!" },
	"Sign in failed": { en: "Sign in failed", ar: "فشل تسجيل الدخول" },
	"Registration failed": { en: "Registration failed", ar: "فشل التسجيل" },
	"Check your email": { en: "Check your email", ar: "تحقق من بريدك الإلكتروني" },
	"We sent a verification link to confirm your account.": { en: "We sent a verification link to confirm your account.", ar: "أرسلنا رابط تحقق لتأكيد حسابك." },
	"Google sign in failed": { en: "Google sign in failed", ar: "فشل تسجيل الدخول عبر Google" },
	"Failed to save": { en: "Failed to save", ar: "فشل الحفظ" },
	"No pending confirmations right now.": { en: "No pending confirmations right now.", ar: "لا توجد تأكيدات معلقة الآن." },
};

type LanguageContextValue = {
	language: Language;
	isArabic: boolean;
	setLanguage: (language: Language) => void;
	t: (text: string) => string;
	formatNumber: (value: number) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
	const [language, setLanguageState] = useState<Language>(() => {
		const stored = localStorage.getItem(STORAGE_KEY);
		return stored === "ar" ? "ar" : "en";
	});

	useEffect(() => {
		localStorage.setItem(STORAGE_KEY, language);
		document.documentElement.lang = language;
		document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
	}, [language]);

	const value = useMemo<LanguageContextValue>(() => {
		const locale = language === "ar" ? "ar-EG" : "en-EG";
		return {
			language,
			isArabic: language === "ar",
			setLanguage: setLanguageState,
			t: (text) => translations[text]?.[language] ?? text,
			formatNumber: (value) => new Intl.NumberFormat(locale).format(value),
		};
	}, [language]);

	return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
	const context = useContext(LanguageContext);
	if (!context) {
		throw new Error("useLanguage must be used within a LanguageProvider");
	}
	return context;
};
